# This file was generated by roxyPackage::roxy.package()
# and will likely be overwritten on its next run.
# Editing is futile.

#' \packageDescription{cocor}
#'
#' The DESCRIPTION file:
#' \tabular{ll}{
#' Package: \tab cocor\cr
#' Type: \tab Package\cr
#' Version: \tab 1.1-4\cr
#' Date: \tab 2022-06-28\cr
#' Depends: \tab methods\cr
#' Enhances: \tab rkward\cr
#' Encoding: \tab UTF-8\cr
#' License: \tab GPL (>= 3)\cr
#' LazyLoad: \tab yes\cr
#' URL: \tab http://comparingcorrelations.org\cr
#' }
#'
#' @title
#' \packageTitle{cocor}
#' @author
#' \packageAuthor{cocor}
#'
#' Maintainer: \packageMaintainer{cocor}
#' @aliases
#' cocor-package NULL
"_PACKAGE"

## usethis namespace: start
## usethis namespace: end
NULL